.gitignore, Makefile, cmd/mms/main.go, cmd/mmsd/main.go
Adds a config file to mmsd as well. Also fixes rebuild with `make all` and `make build_mmsd`.
=> MMSd config file

pkg/mms/events.go
Adding a Close() on NATS connection fixes the problem of messages not being delivered sometimes, when properly closing the connection a Sleep() is not needed in the PostProductEvent function.
=> Add Close() on NATS connection to fix problem of messages not being delivered

cmd/mms/commands.go, cmd/mms/main.go, mms_config_example.yml, pkg/mms/events.go
=> Issue 42: Add JobName and NextEventAt to mms

.gitignore, cmd/mms/commands.go, cmd/mmsd/main.go, internal/server/api.go, internal/server/cache.go, internal/server/cache_test.go, pkg/metaservice/about.go, pkg/metaservice/healthz.go, pkg/metaservice/mockevent.go, pkg/mms/events.go, pkg/mms/events_test.go
Replace single-character variables with more descriptive variable names. Closes #56.
=> Issue 56: Variable Names

internal/server/api.go, internal/server/cache.go
This PR is a step towards solving #57
=> Post Events to Web API

cmd/mms/commands.go, cmd/mms/main.go
Implemented sending over http, currently hardcoded url, and found an issue with database being populated on bad requests.
=> Implement sending over http to api

cmd/mms/commands.go, internal/server/api.go
=> Rename api url from postevent to just events and route the methods

cmd/mmsd/main.go, internal/server/state.go
Add various flags to the `keys` command in `mmsd` to manage the keys database.
=> Key management

cmd/mms/commands.go, cmd/mms/main.go, pkg/mms/events.go
=> Issue #113: Add counter, ntotal and reftime to mms

cmd/mms/commands.go, cmd/mms/main.go
Closes #82 by adding a flag to provide executable or script
=> Issue 82 - Post Processing script or executable

.gitignore, cmd/mmsd/main.go, cmd/mmsd/main_test.go, pkg/mms/events.go
=> Issue120 heartbeat

cmd/mms/commands.go, cmd/mms/main.go, pkg/mms/events.go
**Summary**:
Enables sending of MMD, as part of the MMS payload
**Related issue**: 
Closes #221 
@myggen 
=> Issue221 send mmd

internal/server/events_db.go
**Summary**:
Translates unicode escape characters back to sent tokens.
Closes #222 
@myggen 
=> Unescaped json-payload

cmd/mms/commands.go, internal/server/cache_test.go, internal/server/events_db.go, internal/server/mockevent.go, internal/server/productstatus.go, internal/server/productstatus_test.go, mms_config_example.yml, pkg/mms/events.go, pkg/mms/events_test.go
-Created one custum time type (PEventTime)
-Changed all the time attributes in ProductEvent type to a default time format in UTC implementing marshaler interface
**Summary**:
Closes #159 
=> Change time attributes to a default format in UTC

Dockerfile
**Summary**:close #267
**Related issue**:#267
=> Removed 'USER' instruction from Dockerfile.

.gitignore, cmd/mms/commands.go, cmd/mms/main.go, cmd/mmsd/main.go, internal/server/api.go, internal/server/cache_test.go, internal/server/jwt_db.go, pkg/mms/events.go, pkg/mms/events_test.go
**Summary**: Uses NSC-creds files to create a JWT-db in workdir, this db is used to authorize poster
**Related issue**: Helps close 24 @ MMS repository 
@myggen 
=> Issue 24 kubernetes mmsd

.gitlab-ci.yml
-replaced 'when: always' with 'when: on_success'
**Summary**:
=> Modified gitlab_ci.yml file

Dockerfile
=> updated go version

pkg/mms/events.go
=> Fixed exit before returning log

internal/server/api.go
=> Change /api/v1/events request request timeout from 5 sec to 15 sec
